@extends('web.layouts.master')
@php
$header = \App\Models\PageSetup::page('services');
@endphp
@if(isset($header))

@section('title', content: $service->meta_title)

@section('top_meta_tags')
@if(isset($service->short_desc))
<meta name="description" content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}">
@else
<meta name="description" content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}">
@endif

<script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Product",
      "name": "{{ $service->meta_title }}",
      "image": {
        "@type": "ImageObject",
        "url": "{{ asset('uploads/service/'.$service->image_path) }}",
        "width": "100",
        "height": "100"
      },
      
      "description": "{{ Str::limit(strip_tags($service->description), 500, '...') }}",
      "url": "{{ route('service.single', $service->slug) }}",
      "brand": {
        "@type": "Brand",
        "name": "MSN Softtech",
        "logo": "https://msnsofttech.com/uploads/setting/Untitled-4_1739083515.png"
      },
      "offers": {
        "@type": "Offer",
        "price": "{{ $service->price ?? '999' }}",
        "priceCurrency": "USD",
        "availability": "https://schema.org/InStock",
        "priceValidUntil": "{{ now()->addMonths(6)->format('Y-m-d') }}",
        "hasMerchantReturnPolicy": {
          "@type": "MerchantReturnPolicy",
          "applicableCountry": "US",
          "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
          "returnPolicySeasonalOverride": "https://schema.org/MerchantReturnNotPermitted",
          "returnShippingFeesAmount": {
            "@type": "MonetaryAmount",
            "value": "0.00",
            "currency": "USD"
          },
          "merchantReturnDays": "30",
          "returnMethod": "https://schema.org/ReturnByMail",
          "returnFees": "FreeReturn"
        },
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "shippingRate": {
            "@type": "MonetaryAmount",
            "value": "0.00",
            "currency": "USD"
          },
          "deliveryTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": ["https://schema.org/Monday", "https://schema.org/Tuesday", "https://schema.org/Wednesday", "https://schema.org/Thursday", "https://schema.org/Friday", "https://schema.org/Saturday",
              "https://schema.org/Sunday"]
            },
            "handlingTime": {
              "@type": "QuantitativeValue",
              "minValue": 1,
              "maxValue": 2,
              "unitCode": "DAY"
            },
            "transitTime": {
              "@type": "QuantitativeValue",
              "minValue": 3,
              "maxValue": 5,
              "unitCode": "DAY"
            }
          },
          "shippingDestination": {
            "@type": "DefinedRegion",
            "addressCountry": "US"
          }
        }
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "{{ $service->average_rating }}",
        "bestRating": "5",
        "worstRating": "1",
        "ratingCount": "{{ $service->review_count }}"
      },
      "review": {
        "@type": "Review",
        "author": {
          "@type": "Person",
          "name": "Joseph Garcia"
        },
        "datePublished": "{{ $service->created_at->format('Y-m-d') }}",
        "reviewRating": {
          "@type": "Rating",
          "ratingValue": "5",
          "bestRating": "5",
          "worstRating": "1"
        },
        "reviewBody": "MSN Softtech delivered an exceptional custom {{ $service->short_title }} solution that enhanced our online presence and improved performance."
      }
    }
    </script>
    
    
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

@if(isset($header->meta_keywords))
<meta name="keywords" content="{!! strip_tags($header->meta_keywords) !!}">
@else
<meta name="keywords" content="{!! strip_tags($setting->keywords) !!}">
@endif
@endsection

@endif

@section('social_meta_tags')
@if(isset($setting))
<meta property="og:type" content="website">
<meta property='og:site_name' content="{{ $setting->title }}" />
<meta property='og:title' content="{{ $service->title }}" />
<meta property='og:description' content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}" />
<meta property='og:url' content="{{ route('service.single', $service->slug) }}" />
<meta property='og:image' content="{{ asset('uploads/service/'.$service->image_path) }}" />


<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="{!! '@'.str_replace(' ', '', $setting->title) !!}" />
<meta name="twitter:creator" content="@MSNSOFTTECH" />
<meta name="twitter:url" content="{{ route('service.single', $service->slug) }}" />
<meta name="twitter:title" content="{{ $service->title }}" />
<meta name="twitter:description" content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}" />
<meta name="twitter:image" content="{{ asset('uploads/service/'.$service->image_path) }}" />
@endif
 <!-- ✅ Owl Carousel CSS -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
@endsection

{{-- schema section --}}

@section('content')
<style>
*{
    color: black;
}

    table {
        width: px;
    }

    table,
    table th,
    table td {
        border: solid;
    }

    table th,
    table td {
        border: solid;
    }

    table th>ol>li,
    table td>ul>li,
    table th>ul>li,
    table td>ol>li {
        list-style: initial !important;
        margin-left: 20px;

    }

    .marker {
        background-color: yellow;
    }

    /* </p><table border="1" cellpadding="1" cellspacing="1" style="width:500px">  */

    .description>ul>li {
        margin-left: 30px !important;
        list-style: initial;
        font-size: 16px !important;
    }


    .description>ol>li {
        /* list-style: decimal; */
        margin-left: 30px !important;
        all: revert;
        font-size: 16px !important;
    }


    .description>ul>li>ul>li {
        margin-left: 15px !important;
        list-style: initial;
        font-size: 16px !important;
    }

    .description>ol>li>ol>li {
        margin-left: 15px !important;
        all: revert;
        font-size: 16px !important;
    }

    .description>ol>li>ul>li {
        margin-left: 15px !important;
        list-style: initial;
        font-size: 16px !important;
    }

    .description>ul>li>ol>li {
        margin-left: 15px !important;
        all: revert;
        font-size: 16px !important;
    }

    .description>ul>li>ul {
        margin-left: 0px !important;
        margin-bottom: 15px !important;
        list-style: initial;
        font-size: 16px !important;
    }

    .description>ol>li>ol {
        margin-left: 0px !important;
        margin-bottom: 15px !important;

        all: revert;
        font-size: 16px !important;
    }

    .description>ol>li>ul {
        margin-left: 0px !important;
        margin-bottom: 15px !important;

        list-style: initial;
        font-size: 16px !important;
    }

    .description>ul>li>ol {
        margin-left: 0px !important;
        margin-bottom: 15px !important;
        all: revert;
        font-size: 16px !important;
    }

    .description>p>a {
        color: blue;
        font-weight: bold;
        text-decoration: none !important;
    }
    .description>p>a>b {
        color: blue;
        font-weight: bold;
        text-decoration: none !important;
    }

    .description>p {
        font-size: 18px !important;
        margin-bottom: 0px !important;
        margin-top: 15px !important;
    }
    .description>h2>p{
        font-size: 18px !important;
    }
    .description>h2{
        font-size: 26px !important;
    }

    .description>h3 {
        font-size: 22px !important;
        margin-top: 30px !important;
        margin-bottom: 10px !important;
    }



    .circle-container {
            width: 180px;
            height: 54px;
            background: linear-gradient(135deg, #4CAF50, #2E8B57); /* Green Gradient */
            border-radius: 12px; /* Makes it round */
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
            gap: 15px; /* Space between buttons */
            box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.3);
            /* position: fixed; */
            bottom: 20px;
            right: 20px;
            padding: 15px;
        }

        /* Icon Buttons */
        .circle-button {
            
            background-color: white;
            border: none;
            width: 40px; /* Icon size */
            height: 40px;
            border-radius: 50%; /* Makes buttons round */
            display: flex;
            justify-content: center;
            align-items: center;
            cursor: pointer;
            box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.2);
            transition: all 0.3s ease-in-out;
        }

        /* Hover Effect */
        .circle-button:hover {
            background-color: #2E8B57;
            transform: scale(1.1); /* Slight zoom */
        }

        /* Icon Images */
        .circle-button img {
            width: 25px; /* Adjust icon size */
            height: 25px;
        }
        .hidden { display: none; }

        .cardlink:hover{
            color: red !important;
        }
</style>
<!--Page Title-->
<section class="page-title">
    <div class="container">
        <div class="inner-container clearfix">
            <div class="title-box">
                <h1 style="font-size: 36px">{{ $service->title }}</h1>
            </div>
            <div class="bread-crumb">
                <ul>
                    <li>{{ __('navbar.service-detail') }}</li>
                    <li><a href="{{ route('home') }}">{{ __('navbar.home') }}</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!--End Page Title-->

@if(isset($service))
<!--Sidebar Page Container-->
<div style="background-color: #f7fff9" class="sidebar-page-container">
    <div class="mx-5">
        <div class="row clearfix mb-5">
            <!--Sidebar Side-->
            <div class="sidebar-side col-lg-4 col-md-12 col-sm-12">
                <aside class="sidebar services-sidebar">

                    <!--Service Category Widget-->
                    <div class="sidebar-widget sidebar-blog-category">
                        <ul class="blog-cat">
                            @foreach($service_lists as $service_list)
                            <li class="@if($service_list->id == $service->id) active @endif"><a href="{{ route('service.single', $service_list->slug) }}">{!! str_limit(strip_tags($service_list->short_title), 60, ' ...') !!}</a></li>
                            @endforeach
                        </ul>
                    </div>

                </aside>
            </div>

            <!--Content Side-->
            <div class="content-side col-lg-8 col-md-12 col-sm-12">
                <div class="service-detail">
                    <div class="inner-box">
                        <div class="image-box">
                            <div class="single-item-">
                                <figure class="image"><img style="border-radius: 5px;" src="{{ asset('uploads/service/'.$service->image_path) }}" alt="{{ $service->title }}" /></figure>
                            </div>

                            {{-- <div class="single-item-">
                                <picture>
                                    <source type="image/webp" srcset="{{ asset('uploads/service/'.$service->image_path.'.webp') }}">
                                    <img style="border-radius: 5px;" src="{{ asset('uploads/service/'.$service->image_path) }}" alt="{{ $service->title }}" />
                                </picture>
                            </div> --}}
                            
                        </div>
                        <p style="font-size: 32px; color: black; font-weight: 500;" class="mb-4">{{ $service->short_title }}</p>

                        <div id="processedContent" class="text description">
                        
                            {!! $service->description !!}
                            {{-- {!! str_replace('? <b>', '✅', $service->description) !!} --}}
                            {{-- {!! preg_replace('/\?{1,2} <b>/', '✅', $service->description) !!} --}}
                        </div>
                    </div>
                </div>

                @php
                $page_quote = \App\Models\PageSetup::page('get-quote');
                $page_contact = \App\Models\PageSetup::page('contact-us');
                @endphp
                @if(isset($page_quote))
                <div class="d-flex justify-content-between align-items-center">
                    <div class="circle-container">
                        <!-- Get A Quote Button -->
                        <a href="{{ route('get-quote') }}" target="_blank" class="circle-button">
                            <img src="https://cdn-icons-png.flaticon.com/128/18572/18572275.png" alt="Get A Quote">
                        </a>
                
                        <!-- WhatsApp Button -->
                        <a rel="noopener noreferrer" href="https://wa.link/vkb4au" target="_blank" class="circle-button">
                            <img src="https://cdn-icons-png.flaticon.com/128/733/733585.png" alt="WhatsApp">
                        </a>
                
                        <!-- Email Button -->
                        <a href="mailto:{{$setting->email_one}}?subject=Inquiry&body=Hello, I need your services." class="circle-button">
                            <img src="https://cdn-icons-png.flaticon.com/128/732/732200.png" alt="Email">
                        </a>
                    </div>
                    <div class="">
                        @include('web.layouts.googlemeet')
                    </div>
                </div>
                @elseif(isset($page_contact))
                <a href="{{ route('contact') }}" class="theme-btn btn-style-four mt-3">{{ __('common.get_start') }}</a>
                @endif
            </div>
        </div>


        <div class="">
            <h4 class="mb-4" style="font-weight: 700; text-align: center;">Related Services</h4>
            <div class="row g-1 owl-carousel owl-theme">

                @if (!empty($service->subservices))
                @foreach ($service->subservices as $key => $item)
                    <div class="col-lg-3 col-md-4 col-sm-6 col-12 col-xs-12 mb-3">
                        <div class="card" style="width: 100% !important;">
                            <img src="{{ asset('uploads/service/'.$item->image_path) }}" alt="{{ $item->title }}" class="card-img-top">
                            <div class="card-body">
                                <h6 style="font-weight: 700" class="card-title"><a class="cardlink" href="{{ route('service.related-single',$item->slug) }}">{{ $item->title }}</a></h6>
                            </div>
                        </div>
                    </div>
                @endforeach  
                @endif  
            </div>
        </div>
        
    </div>
</div>
@endif
<script>
        document.addEventListener("DOMContentLoaded", function() {
            // Get the description content
            let descriptionContent = document.querySelector('.text.description').innerHTML;

            // Find the index of the first occurrence of the word "hidden"
            let index = descriptionContent.toLowerCase().indexOf("hidden");

            if (index !== -1) {
                // Show content before the word "hidden"
                let visibleContent = descriptionContent.substring(0, index);
                document.getElementById("processedContent").innerHTML = visibleContent;

                // Hide content after the word "hidden"
                let hiddenContent = descriptionContent.substring(index);
                document.getElementById("processedContent").innerHTML += "<span class='hidden'>" + hiddenContent + "</span>";
            } else {
                // If the word "hidden" is not found, show the entire content
                document.getElementById("processedContent").innerHTML = descriptionContent;
            }
        });
</script>
 <!-- ✅ jQuery -->
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

 <!-- ✅ Owl Carousel JS -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
 <script>
   $(document).ready(function(){
      $('.owl-carousel').owlCarousel({
        loop: true,
        margin: 10,
        nav: true,
        dots: true,
        lazyLoad: true,
        autoplay: false,
        autoplayTimeout: 3000,
        responsive: {
          0: {
            items: 1
          },
          400: {
            items: 2
          },
          800: {
            items: 3
          },
          1200: {
            items: 4
          }
        }
      });
    });
  </script>
@endsection