@extends('web.layouts.master')
@php
$header = \App\Models\PageSetup::page('technology');
@endphp
@if(isset($header))

@section('title', content: $service->meta_title)

@section('top_meta_tags')
@if(isset($service->short_desc))
<meta name="description" content="{!! str_limit(strip_tags($service->short_desc), 200, ' ...') !!}">
@else
<meta name="description" content="{!! str_limit(strip_tags($service->short_desc), 200, ' ...') !!}">
@endif
{{-- 
<script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Product",
      "name": "{{ $service->meta_title }}",
      "image": {
        "@type": "ImageObject",
        "url": "{{ asset('uploads/service/'.$service->image_path) }}",
        "width": "100",
        "height": "100"
      },
      
      "description": "{{ Str::limit(strip_tags($service->description), 500, '...') }}",
      "url": "{{ route('service.technology', $service->slug) }}",
      "brand": {
        "@type": "Brand",
        "name": "MSN Softtech",
        "logo": "https://msnsofttech.com/uploads/setting/Untitled-4_1739083515.png"
      },
      "offers": {
        "@type": "Offer",
        "price": "{{ $service->price ?? '999' }}",
        "priceCurrency": "USD",
        "availability": "https://schema.org/InStock",
        "priceValidUntil": "{{ now()->addMonths(6)->format('Y-m-d') }}",
        "hasMerchantReturnPolicy": {
          "@type": "MerchantReturnPolicy",
          "applicableCountry": "US",
          "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
          "returnPolicySeasonalOverride": "https://schema.org/MerchantReturnNotPermitted",
          "returnShippingFeesAmount": {
            "@type": "MonetaryAmount",
            "value": "0.00",
            "currency": "USD"
          },
          "merchantReturnDays": "30",
          "returnMethod": "https://schema.org/ReturnByMail",
          "returnFees": "FreeReturn"
        },
        "shippingDetails": {
          "@type": "OfferShippingDetails",
          "shippingRate": {
            "@type": "MonetaryAmount",
            "value": "0.00",
            "currency": "USD"
          },
          "deliveryTime": {
            "@type": "ShippingDeliveryTime",
            "businessDays": {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": ["https://schema.org/Monday", "https://schema.org/Tuesday", "https://schema.org/Wednesday", "https://schema.org/Thursday", "https://schema.org/Friday", "https://schema.org/Saturday",
              "https://schema.org/Sunday"]
            },
            "handlingTime": {
              "@type": "QuantitativeValue",
              "minValue": 1,
              "maxValue": 2,
              "unitCode": "DAY"
            },
            "transitTime": {
              "@type": "QuantitativeValue",
              "minValue": 3,
              "maxValue": 5,
              "unitCode": "DAY"
            }
          },
          "shippingDestination": {
            "@type": "DefinedRegion",
            "addressCountry": "US"
          }
        }
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "{{ $service->average_rating }}",
        "bestRating": "5",
        "worstRating": "1",
        "ratingCount": "{{ $service->review_count }}"
      },
      "review": {
        "@type": "Review",
        "author": {
          "@type": "Person",
          "name": "Joseph Garcia"
        },
        "datePublished": "{{ $service->created_at->format('Y-m-d') }}",
        "reviewRating": {
          "@type": "Rating",
          "ratingValue": "5",
          "bestRating": "5",
          "worstRating": "1"
        },
        "reviewBody": "MSN Softtech delivered an exceptional custom {{ $service->short_title }} solution that enhanced our online presence and improved performance."
      }
    }
    </script> --}}
    
    
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

@if(isset($service->keywords))
<meta name="keywords" content="{!! strip_tags($service->keywords) !!}">
@else
<meta name="keywords" content="{!! strip_tags($setting->keywords) !!}">
@endif
@endsection

@endif

@section('social_meta_tags')
@if(isset($setting))
<meta property="og:type" content="website">
<meta property='og:site_name' content="{{ $setting->title }}" />
<meta property='og:title' content="{{ $service->meta_title }}" />
<meta property='og:description' content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}" />
<meta property='og:url' content="{{ route('service.technology', $service->slug) }}" />
<meta property='og:image' content="{{ asset('uploads/service/'.$service->image_path) }}" />


<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="{!! '@'.str_replace(' ', '', $setting->title) !!}" />
<meta name="twitter:creator" content="@MSNSOFTTECH" />
<meta name="twitter:url" content="{{ route('service.technology', $service->slug) }}" />
<meta name="twitter:title" content="{{ $service->meta_title }}" />
<meta name="twitter:description" content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}" />
<meta name="twitter:image" content="{{ asset('uploads/service/'.$service->image_path) }}" />
@endif
@endsection

{{-- schema section --}}

@section('content')
{{-- <style>
*{
    color: black;
}

    table {
        width: px;
    }

    table,
    table th,
    table td {
        border: solid;
    }

    table th,
    table td {
        border: solid;
    }

    table th>ol>li,
    table td>ul>li,
    table th>ul>li,
    table td>ol>li {
        list-style: initial !important;
        margin-left: 20px;

    }

    .marker {
        background-color: yellow;
    }

    /* </p><table border="1" cellpadding="1" cellspacing="1" style="width:500px">  */

    .description>ul>li {
        margin-left: 30px !important;
        list-style: initial;
        font-size: 16px !important;
    }


    .description>ol>li {
        /* list-style: decimal; */
        margin-left: 30px !important;
        all: revert;
        font-size: 16px !important;
    }


    .description>ul>li>ul>li {
        margin-left: 15px !important;
        list-style: initial;
        font-size: 16px !important;
    }

    .description>ol>li>ol>li {
        margin-left: 15px !important;
        all: revert;
        font-size: 16px !important;
    }

    .description>ol>li>ul>li {
        margin-left: 15px !important;
        list-style: initial;
        font-size: 16px !important;
    }

    .description>ul>li>ol>li {
        margin-left: 15px !important;
        all: revert;
        font-size: 16px !important;
    }

    .description>ul>li>ul {
        margin-left: 0px !important;
        margin-bottom: 15px !important;
        list-style: initial;
        font-size: 16px !important;
    }

    .description>ol>li>ol {
        margin-left: 0px !important;
        margin-bottom: 15px !important;

        all: revert;
        font-size: 16px !important;
    }

    .description>ol>li>ul {
        margin-left: 0px !important;
        margin-bottom: 15px !important;

        list-style: initial;
        font-size: 16px !important;
    }

    .description>ul>li>ol {
        margin-left: 0px !important;
        margin-bottom: 15px !important;
        all: revert;
        font-size: 16px !important;
    }

    .description>p>a {
        color: blue;
        font-weight: bold;
        text-decoration: none !important;
    }
    .description>p>a>b {
        color: blue;
        font-weight: bold;
        text-decoration: none !important;
    }

    .description>p {
        font-size: 18px !important;
        margin-bottom: 0px !important;
        margin-top: 15px !important;
    }
    .description>h2>p{
        font-size: 18px !important;
    }
    .description>h2{
        font-size: 26px !important;
    }

    .description>h3 {
        font-size: 22px !important;
        margin-top: 30px !important;
        margin-bottom: 10px !important;
    }



    .circle-container {
            width: 180px;
            height: 54px;
            background: linear-gradient(135deg, #4CAF50, #2E8B57); /* Green Gradient */
            border-radius: 12px; /* Makes it round */
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
            gap: 15px; /* Space between buttons */
            box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.3);
            /* position: fixed; */
            bottom: 20px;
            right: 20px;
            padding: 15px;
        }

        /* Icon Buttons */
        .circle-button {
            
            background-color: white;
            border: none;
            width: 40px; /* Icon size */
            height: 40px;
            border-radius: 50%; /* Makes buttons round */
            display: flex;
            justify-content: center;
            align-items: center;
            cursor: pointer;
            box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.2);
            transition: all 0.3s ease-in-out;
        }

        /* Hover Effect */
        .circle-button:hover {
            background-color: #2E8B57;
            transform: scale(1.1); /* Slight zoom */
        }

        /* Icon Images */
        .circle-button img {
            width: 25px; /* Adjust icon size */
            height: 25px;
        }
        .hidden { display: none; }

/* banner */
    .banner-container {
    display: flex;
    flex-direction: column;
    /* padding: 4rem 1.5rem; */
    gap: 2rem;
    max-height: 100vh;
    overflow: hidden;

    background-color: #0B1C3A;
    color: white;
    font-family: Arial, sans-serif;
   
  }

  @media (min-width: 768px) {
    .banner-container {
      flex-direction: row;
      justify-content: space-between;
      align-items: flex-start;
      /* padding: 4rem 5%; */
      gap: 2rem;
    }

    .banner-left, .banner-card {
      flex: 1;
      max-width: 50%;
    }

    .banner-left {
      padding-right: 2rem;
    }

    .banner-card {
      padding-left: 2rem;
    }
  }

  .banner-left {
    max-width: 600px;
  }

  h1 {
    font-size: 2.5rem;
    font-weight: bold;
    margin-bottom: 1.5rem;
  }

  p {
    font-size: 1.125rem;
    line-height: 1.6;
    margin-bottom: 1.5rem;
  }

  .banner-card {
    background-color: #05264E;
    border: 1px solid #00FF87;
    padding: 1.5rem;
    border-radius: 1rem;
    width: 100%;
    max-width: 400px;
    margin-top: 0;
  }

  .banner-card img {
    height: 56px;
    display: block;
    margin: 0 auto 1rem auto;
  }

  .banner-card h2 {
    text-align: center;
    font-size: 1.25rem;
    font-weight: bold;
    margin-bottom: 1rem;
  }

  .banner-card span {
    text-decoration: underline;
  }

  .banner-cta-button {
    background-color: #F97316;
    color: white;
    padding: 0.75rem 1.5rem;
    border-radius: 0.5rem;
    font-size: 1.125rem;
    font-weight: bold;
    border: none;
    width: 100%;
    cursor: pointer;
    margin-bottom: 1.5rem;
  }

  .banner-cta-button:hover {
    background-color: #ea580c;
  }

  .banner-info-box {
    background-color: #1E3A8A;
    padding: 1rem;
    border-radius: 0.5rem;
    font-size: 0.875rem;
    text-align: center;
  }

  .banner-info-box p {
    margin-bottom: 0.5rem;
  }
</style> --}}

{{-- <link rel="stylesheet" href="{{ asset('web/css/extra-technology.css') }}">     --}}
<!--Page Title-->
{{-- <section class="page-title">
    <div class="container">
        <div class="inner-container clearfix">
            <div class="title-box">
                <h1 style="font-size: 36px">{{ $service->title }}</h1>
            </div>
            <div class="bread-crumb">
                <ul>
                    <li>{{ __('navbar.service-detail') }}</li>
                    <li><a href="{{ route('home') }}">{{ __('navbar.home') }}</a></li>
                </ul>
            </div>
        </div>
    </div>
</section> --}}
{{-- <section style="padding:20px 60px !important;" class="banner-container">
    <div class="banner-left">
      <h1 style="color: white" >{{ $service->short_title }}</h1>
      <p style="color: white">Hire our expert Python developers to build scalable web applications, data-driven solutions, and advanced machine learning models tailored to your business needs.</p>
    </div>

    <div class="banner-card">
      <img src="{{ asset('uploads/service/'.$service->logo_path) }}" alt="{{ $service->title }}" />
      <h2 style="color: white">
        Get <span style="color: white">Project-based</span> and <br/>
        <span style="color: white">Dedicated Teams</span> from a<br/>
        <span style="color: white">Highest-rated Company</span>.
      </h2>
      <button id="open-modal" class="banner-cta-button">Discuss Your Requirements →</button>
      <div class="banner-info-box">
        <p style="color: white"><strong style="color: white">Ready to bring your project to life?</strong></p>
        <p style="color: white">Got a project in mind? Share your vision, and get a free expert consultation within 24 hours—complete with a personalized roadmap tailored to your goals and budget.</p>
      </div>
    </div>
  </section>
@if(isset($service))
<div style="background-color: #ffffff" class="sidebar-page-container">
    <div class="mx-5">
        <div class="row clearfix mb-5">
            <div class="sidebar-side col-lg-4 col-md-12 col-sm-12">
                <aside class="sidebar services-sidebar">

                    <div class="sidebar-widget sidebar-blog-category">
                        <ul class="blog-cat">
                            @foreach($service_lists as $service_list)
                            <li class="@if($service_list->id == $service->id) active @endif"><a href="{{ route('service.technology', $service_list->slug) }}">{!! str_limit(strip_tags($service_list->title), 60, ' ...') !!}</a></li>
                            @endforeach
                        </ul>
                    </div>

                </aside>
            </div>

            <div class="content-side col-lg-8 col-md-12 col-sm-12">
                <div class="service-detail">
                    <div class="inner-box">
                        <div class="image-box">
                            <div class="single-item-">
                                <figure class="image"><img style="border-radius: 5px;" src="{{ asset('uploads/service/'.$service->image_path) }}" alt="{{ $service->title }}" /></figure>
                            </div>

                            <div class="single-item-">
                                <picture>
                                    <source type="image/webp" srcset="{{ asset('uploads/service/'.$service->image_path.'.webp') }}">
                                    <img style="border-radius: 5px;" src="{{ asset('uploads/service/'.$service->image_path) }}" alt="{{ $service->title }}" />
                                </picture>
                            </div>
                            
                        </div>
                        <p style="font-size: 32px; color: black; font-weight: 500;" class="mb-4">{{ $service->title }}</p>

                        <div id="processedContent" style="margin-top: 0px !important" class="text description">
                        
                            {!! $service->description !!}
                        
                        </div>
                    </div>
                </div>

                @php
                $page_quote = \App\Models\PageSetup::page('get-quote');
                $page_contact = \App\Models\PageSetup::page('contact-us');
                @endphp
                @if(isset($page_quote))
                <div class="d-flex justify-content-between align-items-center">
                    <div class="circle-container">
                        <a href="{{ route('get-quote') }}" target="_blank" class="circle-button">
                            <img src="https://cdn-icons-png.flaticon.com/128/18572/18572275.png" alt="Get A Quote">
                        </a>
                
                        <a rel="noopener noreferrer" href="https://wa.link/vkb4au" target="_blank" class="circle-button">
                            <img src="https://cdn-icons-png.flaticon.com/128/733/733585.png" alt="WhatsApp">
                        </a>
                
                        <a href="mailto:{{$setting->email_one}}?subject=Inquiry&body=Hello, I need your services." class="circle-button">
                            <img src="https://cdn-icons-png.flaticon.com/128/732/732200.png" alt="Email">
                        </a>
                    </div>
                    <div class="">
                        @include('web.layouts.googlemeet')
                    </div>
                </div>
                @elseif(isset($page_contact))
                <a href="{{ route('contact') }}" class="theme-btn btn-style-four mt-3">{{ __('common.get_start') }}</a>
                @endif
            </div>
        </div>

        @if ($service->subservices)
        @foreach ($service->subservices as $key => $item)
        @php
            if (stripos($item->description, 'hidden') !== false) {
                $cleanDescription = Str::before($item->description, 'hidden');
            } else {
                $cleanDescription = $item->description;
            }
        @endphp
        @if ($key % 2 == 1)
            
        <div class="row clearfix mb-5">
            <div class="sidebar-side col-lg-5 col-md-12 col-sm-12">
                <aside class="sidebar services-sidebar">

                    <div class="image-box">
                        <div class="single-item-">
                            <figure class="image"><img style="border-radius: 10px;" src="{{ asset('uploads/service/'.$item->image_path) }}" alt="{{ $item->title }}" /></figure>
                        </div>
                    </div>
                    <div class="image-box">
                        <div class="single-item-">
                            <figure class="image">
                                <picture>
                                    <source type="image/webp" srcset="{{ asset('uploads/service/'.$item->image_path.'.webp') }}">
                                    <img style="border-radius: 10px;" src="{{ asset('uploads/service/'.$item->image_path) }}" alt="{{ $item->title }}" />
                                </picture>
                            </figure>
                        </div>
                    </div>
                    

                </aside>
            </div>

            <div class="content-side col-lg-7 col-md-12 col-sm-12">
                <div class="service-detail">
                    <div class="inner-box">
                        
                       <h2 style="font-size: 30px;" class="mb-3">{{ $item->title }}</h2>
                        <div id="processedContent" class="text description">
                            {!! $cleanDescription !!}
                        </div>
                    
                    </div>
                </div>

                @php
                $page_quote = \App\Models\PageSetup::page('get-quote');
                $page_contact = \App\Models\PageSetup::page('contact-us');
                @endphp
                @if(isset($page_quote))
                <div class="circle-container">
                    <a href="{{ route('get-quote') }}" target="_blank" class="circle-button">
                        <img src="https://cdn-icons-png.flaticon.com/128/18572/18572275.png" alt="Get A Quote">
                    </a>
                    <a rel="noopener noreferrer" href="https://wa.link/vkb4au" target="_blank" class="circle-button">
                        <img src="https://cdn-icons-png.flaticon.com/128/733/733585.png" alt="WhatsApp">
                    </a>
                    
                    <a href="mailto:{{$setting->email_one}}?subject=Inquiry&body={{ $item->title}}" class="circle-button">
                        <img src="https://cdn-icons-png.flaticon.com/128/732/732200.png" alt="Email">
                    </a>
                </div>
                @elseif(isset($page_contact))
                <a href="{{ route('contact') }}" class="theme-btn btn-style-four mt-3">{{ __('common.get_start') }}</a>
                @endif
                
            </div>
        </div>
        @else
        <div class="row clearfix mb-5">
            <div class="content-side col-lg-7 col-md-12 col-sm-12">
                <div class="service-detail">
                    <div class="inner-box">
                       
                        <h2 class=" mb-3" style="font-size: 30px;">{{ $item->title }}</h2>

                        <div id="processedContent" class="text description">
                            
                            {!! $cleanDescription !!}
                        </div>
                    </div>
                </div>

                @php
                $page_quote = \App\Models\PageSetup::page('get-quote');
                $page_contact = \App\Models\PageSetup::page('contact-us');
                @endphp
                @if(isset($page_quote))
                <div class="circle-container">
                    <a href="{{ route('get-quote') }}" target="_blank" class="circle-button">
                        <img src="https://cdn-icons-png.flaticon.com/128/18572/18572275.png" alt="Get A Quote">
                    </a>
                    <a rel="noopener noreferrer" href="https://wa.link/vkb4au" target="_blank" class="circle-button">
                        <img src="https://cdn-icons-png.flaticon.com/128/733/733585.png" alt="WhatsApp">
                    </a>
                    
                    <a href="mailto:{{$setting->email_one}}?subject=Inquiry&body={{ $item->title}}" class="circle-button">
                        <img src="https://cdn-icons-png.flaticon.com/128/732/732200.png" alt="Email">
                    </a>
                </div>
                @elseif(isset($page_contact))
                <a href="{{ route('contact') }}" class="theme-btn btn-style-four mt-3">{{ __('common.get_start') }}</a>
                @endif

            </div>

            <div class="sidebar-side col-lg-5 col-md-12 col-sm-12">
                <aside class="sidebar services-sidebar">

                    <div class="image-box">
                        <div class="single-item-">
                            <figure class="image"><img style="border-radius: 10px;" src="{{ asset('uploads/service/'.$item->image_path) }}" alt="{{ $item->title }}" /></figure>
                        </div>
                    </div>
                    <div class="image-box">
                        <div class="single-item-">
                            <figure class="image">
                                <picture>
                                    <source type="image/webp" srcset="{{ asset('uploads/service/'.$item->image_path.'.webp') }}">
                                    <img style="border-radius: 10px;" src="{{ asset('uploads/service/'.$item->image_path) }}" alt="{{ $item->title }}" />
                                </picture>
                            </figure>
                        </div>
                    </div>
                    

                </aside>
            </div>
        </div>
        @endif
        @endforeach
        @endif

    

    </div>
</div>
@endif
<script>
        document.addEventListener("DOMContentLoaded", function() {
            // Get the description content
            let descriptionContent = document.querySelector('.text.description').innerHTML;

            // Find the index of the first occurrence of the word "hidden"
            let index = descriptionContent.toLowerCase().indexOf("hidden");

            if (index !== -1) {
                // Show content before the word "hidden"
                let visibleContent = descriptionContent.substring(0, index);
                document.getElementById("processedContent").innerHTML = visibleContent;

                // Hide content after the word "hidden"
                let hiddenContent = descriptionContent.substring(index);
                document.getElementById("processedContent").innerHTML += "<span class='hidden'>" + hiddenContent + "</span>";
            } else {
                // If the word "hidden" is not found, show the entire content
                document.getElementById("processedContent").innerHTML = descriptionContent;
            }
        });
</script> --}}
<style>
    /* ---------- HERO SECTION ---------- */
.hero {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background: linear-gradient(135deg, #0a2b47, #0c2340);
  color: white;
  padding: 0 60px;
  height: 450px;       /* fixed height */
  overflow: hidden;    /* prevent content overflow */
}

/* Left Side */
.hero-left {
  max-width: 55%;
}

.hero-left h1 {
  font-size: 40px;     /* reduced */
  font-weight: 800;
  margin-bottom: 15px;
  line-height: 1.2;
}

.hero-left p {
  font-size: 18px;     /* reduced */
  line-height: 1.6;
  margin-bottom: 25px;
  font-weight: 500;
  color: #ffffff;
}

/* Reviews Box */
.reviews-box {
  border: 1px solid rgba(255, 255, 255, 0.3);
  border-radius: 8px;
  padding: 15px 20px;   /* reduced */
  max-width: 600px;
}

.reviews-box p {
  font-weight: 500;
  margin-bottom: 15px;
  font-size: 15px;
}

.reviews-logos {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.review-item {
  text-align: center;
}

.review-item img {
  height: 24px;       /* reduced */
  margin-bottom: 8px;
}

.stars {
  color: #ffc107;
  font-size: 14px;    /* reduced */
  letter-spacing: 1.5px;
}

/* Right Side Card */
.hero-right {
  max-width: 360px;
}

.card {
  background: #0c2340;
  padding: 25px 20px;   /* reduced */
  border: 2px solid #1ec876;
  border-radius: 12px;
  text-align: center;
  position: relative;
}

.vue-icon {
  position: absolute;
  top: -30px;          /* reduced */
  left: 50%;
  transform: translateX(-50%);
  background: #0c2340;
  padding: 8px 16px;
  border-radius: 8px;
}

.vue-icon img {
  height: 45px;        /* reduced */
}

.card h3 {
  font-size: 18px;     /* reduced */
  margin: 35px 0 20px;
  font-weight: 600;
  line-height: 1.4;
}

.orange-btn {
  display: inline-block;
  background: #052C58;
  color: white;
  padding: 12px 20px;  /* reduced */
  border-radius: 6px;
  text-decoration: none;
  font-weight: 600;
  margin-bottom: 20px;
  transition: 0.3s;
  font-size: 15px;
}

.orange-btn:hover {
    background: #052C58;
    color: white;
}

.blue-box {
  background: #153b7d;
  padding: 15px;       /* reduced */
  border-radius: 10px;
  text-align: left;
}

.blue-box h4 {
  margin-bottom: 8px;
  font-size: 15px;     /* reduced */
  font-weight: 700;
}

.blue-box p {
  font-size: 13px;     /* reduced */
  line-height: 1.4;
  font-weight: 400;
  color: #ffffff;
}



/*  */
        section {
            font-family: "Poppins", sans-serif;
            /* background: #fff; */
            color: #222;
        }

        h1,
        h2 {
            font-weight: 700;
        }

        .lead-text {
            color: #555;
            font-size: 1rem;
            line-height: 1.6;
        }

        /* --- Service Cards --- */
        .service-card {
            background: #fff;
            border: 1px solid #e2e7ea;
            border-radius: 10px;
            padding: 18px;
            margin-bottom: 16px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.04);
            cursor: pointer;
            transition: all .2s ease;
        }

        .service-card:hover {
            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.08);
        }

        .service-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .service-title {
            font-weight: 700;
            font-size: 1rem;
            margin: 0;
        }

        .toggle-btn {
            width: 30px;
            height: 30px;
            display: flex;
            align-items: center;
            justify-content: center;
            border: 1px solid #d0d6db;
            border-radius: 6px;
            font-weight: 700;
            background: #fff;
        }

        .service-desc {
            max-height: 0;
            overflow: hidden;
            transition: max-height .3s ease;
            font-size: .9rem;
            text-align: left;
            color: #444;
            margin-top: 10px;
        }

        .service-card.active .service-desc {
            max-height: 400px;
        }

        .service-card.active .toggle-btn {
            background: #052C58;
            color: #fff;
            border-color: #052C58;
        }

        .main-cta {
            margin-top: 20px;
            background: #052C58;
            border: none;
            border-radius: 8px;
            padding: 12px 26px;
            font-weight: 700;
            color: #fff;
            box-shadow: 0 6px 16px rgba(255, 106, 0, 0.2);
        }

        /* --- Expertise Section --- */
        .expertise {
            background: #fbfbfd;
            padding: 60px 0;
            text-align: center;
            margin-top: 50px;
        }

        .expertise h2 {
            font-weight: 700;
            margin-bottom: 10px;
        }

        .expertise .sub {
            color: #2fbf76;
            font-weight: 600;
            margin-bottom: 30px;
        }

        .tech-pill {
            background: #fff;
            padding: 18px 22px;
            border-radius: 10px;
            border: 1px solid #e5e9ec;
            box-shadow: 0 6px 16px rgba(0, 0, 0, 0.05);
            margin: 10px;
        }

        .start-trial {
            margin-top: 28px;
            background: #052C58;
            border-radius: 8px;
            color: #ffffff;
            padding: 12px 26px;
            font-weight: 700;
            display: inline-block;
            box-shadow: 0 8px 24px rgba(255, 106, 0, 0.2);
            text-decoration: none;
        }
        .start-trial:hover {
            color: #ffffff;
        }

</style>

{{--  --}}
<section class="hero">
    <!-- Left Side -->
    <div class="hero-left">
      <h1>Hire Vue.js Developers</h1>
      <p>
        Hire our Vue.js developers to build engaging user interfaces, dynamic single-page 
        applications, and interactive web solutions tailored to your business needs.
      </p>

      <!-- Reviews Box -->
      <div class="reviews-box">
        <p>300+ Glowing 5-Star Reviews</p>
        <div class="reviews-logos">
          <div class="review-item">
            <img src="//cdn.worldvectorlogo.com/logos/clutchco.svg" alt="Clutch">
            <div class="stars">★★★★★</div>
          </div>
          <div class="review-item">
            <img src="//vectorseek.com/wp-content/uploads/2023/09/Goodfirms-Logo-Vector.svg-.png" alt="GoodFirms">
            <div class="stars">★★★★★</div>
          </div>
          <div class="review-item">
            <img src="//images.seeklogo.com/logo-png/40/3/g2-logo-png_seeklogo-407782.png" alt="G2">
            <div class="stars">★★★★★</div>
          </div>
          <div class="review-item">
            <img src="//upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg" alt="Google">
            <div class="stars">★★★★★</div>
          </div>
        </div>
      </div>
    </div>

    <!-- Right Side -->
    <div class="hero-right">
      <div class="card">
        <div class="vue-icon">
          <img src="https://vuejs.org/images/logo.png" alt="Vue Logo">
        </div>
        <h3>Get <span style="color:#f15a29">Teams</span> or Fixed-Cost Solutions from a Global Partner.</h3>
        <a href="#" class="orange-btn">Discuss Your Requirements →</a>
        <div class="blue-box">
          <h4>Ready to bring your project to life?</h4>
          <p>
            Share your vision, and we'll provide a free expert consultation within 24 hours,
            outlining a clear path to success tailored to your project and budget.
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- TOP SECTION -->
    <section class="py-5 text-center">
        <div class="container">
            <h1 style="font-weight: 900">Hire Vue.js Developers to Create Interactive User Interfaces with Ease</h1>
            <p class="lead-text mt-3 mb-5">
                Our Vue.js developers build intuitive user interfaces for websites and single-page applications,
                making the user experience simpler and more enjoyable. Using a component-based programming model,
                they efficiently develop user interfaces of any complexity, ensuring robust and scalable solutions as
                per your project needs.
            </p>

            <div class="row justify-content-center">
                <!-- <div class="col-lg-4">
          
        </div> -->

                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-md-4">
                            <!-- Card 1 -->
                            <div class="service-card">
                                <div class="service-header">
                                    <p class="service-title">Vue.js Front-end Development</p>
                                    <div class="toggle-btn">+</div>
                                </div>
                                <div class="service-desc">
                                    Our team of UI/UX designers and Vue.js developers creates fast, interactive, and
                                    visually appealing user interfaces. We utilize reactive data binding, virtual DOM,
                                    and component-based architecture to ensure your web applications are highly
                                    responsive and efficient and deliver a seamless and engaging user experience.
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <!-- Card 2 -->
                            <div class="service-card">
                                <div class="service-header">
                                    <p class="service-title">Single-Page Application Development</p>
                                    <div class="toggle-btn">+</div>
                                </div>
                                <div class="service-desc">
                                    We specialize in SPAs using Vue.js to provide smooth navigation, fast performance,
                                    and excellent UX for complex apps.
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="service-card">
                                <div class="service-header">
                                    <p class="service-title">Custom Vue.js Web Development</p>
                                    <div class="toggle-btn">+</div>
                                </div>
                                <div class="service-desc">
                                    Tailored Vue.js applications with custom UX/UI, component libraries, and performance
                                    optimization.
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="service-card">
                                <div class="service-header">
                                    <p class="service-title">Vue.js Staff Augmentation</p>
                                    <div class="toggle-btn">+</div>
                                </div>
                                <div class="service-desc">
                                    Scale your team with skilled Vue.js developers on demand for flexible project needs.
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="service-card">
                                <div class="service-header">
                                    <p class="service-title">Real-time Application Development</p>
                                    <div class="toggle-btn">+</div>
                                </div>
                                <div class="service-desc">
                                    Build powerful real-time apps like dashboards, chat apps, and collaboration tools
                                    with Vue.js and sockets.
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="service-card">
                                <div class="service-header">
                                    <p class="service-title">Vue.js Maintenance & Support</p>
                                    <div class="toggle-btn">+</div>
                                </div>
                                <div class="service-desc">
                                    Continuous support, monitoring, and updates to keep your Vue.js applications running
                                    smoothly.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button class="main-cta">Book A Developer Interview Session →</button>
        </div>
    </section>

    <!-- BOTTOM SECTION -->
    <section class="expertise">
        <div class="container">
            <h2>Technical Expertise of Our Vue.js Developers</h2>
            <p class="sub">Hire Vue.js Programmers Trusted by 98% of CTOs!</p>

            <div class="row justify-content-center">
                <div class="col-md-3 col-sm-6">
                    <div class="tech-pill"><img src="//www.capitalnumbers.com/images/svg_logos/reactjs/vuetify.svg" alt="Vuetify"
                            style="max-height:34px;"></div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="tech-pill"><img src="//www.capitalnumbers.com/images/svg_logos/reactjs/bootstrap-vue.svg" alt="BootstrapVue"
                            style="max-height:34px;"></div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="tech-pill"><img src="//www.capitalnumbers.com/images/svg_logos/reactjs/nuxt.svg" alt="Nuxt"
                            style="max-height:34px;"></div>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-md-3 col-sm-6">
                    <div class="tech-pill"><img src="//www.capitalnumbers.com/images/svg_logos/reactjs/vuex.svg" alt="Vuex"
                            style="max-height:36px;"></div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="tech-pill"><img src="//www.capitalnumbers.com/images/svg_logos/reactjs/vuelidate.svg" alt="Vuelidate"
                            style="max-height:36px;"></div>
                </div>
            </div>

            <a class="start-trial text-white" >Start 1-Week Free Trial →</a>
        </div>
    </section>

    <script>
        // Toggle each card independently
        document.querySelectorAll('.service-card').forEach(card => {
            card.addEventListener('click', () => {
                card.classList.toggle('active');
                const btn = card.querySelector('.toggle-btn');
                btn.textContent = card.classList.contains('active') ? '−' : '+';
            });
        });
    </script>
@endsection