@extends('web.layouts.master')
@php
  $header = \App\Models\PageSetup::page('services');
@endphp
@if(isset($header))

@section('title', content: $service->meta_title)

@section('top_meta_tags')
  @if(isset($service->short_desc))
    <meta name="description" content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}">
  @else
    <meta name="description" content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}">
  @endif

  <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Product",
        "name": "{{ $service->meta_title }}",
        "image": {
          "@type": "ImageObject",
          "url": "{{ asset('uploads/service/' . $service->image_path) }}",
          "width": "100",
          "height": "100"
        },

        "description": "{{ Str::limit(strip_tags($service->description), 500, '...') }}",
        "url": "{{ route('service.single', $service->slug) }}",
        "brand": {
          "@type": "Brand",
          "name": "MSN Softtech",
          "logo": "https://msnsofttech.com/uploads/setting/Untitled-4_1739083515.png"
        },
        "offers": {
          "@type": "Offer",
          "price": "{{ $service->price ?? '999' }}",
          "priceCurrency": "USD",
          "availability": "https://schema.org/InStock",
          "priceValidUntil": "{{ now()->addMonths(6)->format('Y-m-d') }}",
          "hasMerchantReturnPolicy": {
            "@type": "MerchantReturnPolicy",
            "applicableCountry": "US",
            "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
            "returnPolicySeasonalOverride": "https://schema.org/MerchantReturnNotPermitted",
            "returnShippingFeesAmount": {
              "@type": "MonetaryAmount",
              "value": "0.00",
              "currency": "USD"
            },
            "merchantReturnDays": "30",
            "returnMethod": "https://schema.org/ReturnByMail",
            "returnFees": "FreeReturn"
          },
          "shippingDetails": {
            "@type": "OfferShippingDetails",
            "shippingRate": {
              "@type": "MonetaryAmount",
              "value": "0.00",
              "currency": "USD"
            },
            "deliveryTime": {
              "@type": "ShippingDeliveryTime",
              "businessDays": {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": ["https://schema.org/Monday", "https://schema.org/Tuesday", "https://schema.org/Wednesday", "https://schema.org/Thursday", "https://schema.org/Friday", "https://schema.org/Saturday",
                "https://schema.org/Sunday"]
              },
              "handlingTime": {
                "@type": "QuantitativeValue",
                "minValue": 1,
                "maxValue": 2,
                "unitCode": "DAY"
              },
              "transitTime": {
                "@type": "QuantitativeValue",
                "minValue": 3,
                "maxValue": 5,
                "unitCode": "DAY"
              }
            },
            "shippingDestination": {
              "@type": "DefinedRegion",
              "addressCountry": "US"
            }
          }
        },
        "aggregateRating": {
          "@type": "AggregateRating",
          "ratingValue": "{{ $service->average_rating }}",
          "bestRating": "5",
          "worstRating": "1",
          "ratingCount": "{{ $service->review_count }}"
        },
        "review": {
          "@type": "Review",
          "author": {
            "@type": "Person",
            "name": "Joseph Garcia"
          },
          "datePublished": "{{ $service->created_at->format('Y-m-d') }}",
          "reviewRating": {
            "@type": "Rating",
            "ratingValue": "5",
            "bestRating": "5",
            "worstRating": "1"
          },
          "reviewBody": "MSN Softtech delivered an exceptional custom {{ $service->short_title }} solution that enhanced our online presence and improved performance."
        }
      }
      </script>

  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

  @if(isset($header->meta_keywords))
    <meta name="keywords" content="{!! strip_tags($header->meta_keywords) !!}">
  @else
    <meta name="keywords" content="{!! strip_tags($setting->keywords) !!}">
  @endif
@endsection

@endif

@section('social_meta_tags')
  @if(isset($setting))
    <meta property="og:type" content="website">
    <meta property='og:site_name' content="{{ $setting->title }}" />
    <meta property='og:title' content="{{ $service->title }}" />
    <meta property='og:description' content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}" />
    <meta property='og:url' content="{{ route('service.single', $service->slug) }}" />
    <meta property='og:image' content="{{ asset('uploads/service/' . $service->image_path) }}" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="{!! '@' . str_replace(' ', '', $setting->title) !!}" />
    <meta name="twitter:creator" content="@MSNSOFTTECH" />
    <meta name="twitter:url" content="{{ route('service.single', $service->slug) }}" />
    <meta name="twitter:title" content="{{ $service->title }}" />
    <meta name="twitter:description" content="{!! str_limit(strip_tags($service->short_desc), 160, ' ...') !!}" />
    <meta name="twitter:image" content="{{ asset('uploads/service/' . $service->image_path) }}" />
  @endif
@endsection

{{-- ============================================================
     SINGLE SERVICE — "SERVICE DOSSIER" REDESIGN
     Concept: the page reads like an engineering spec sheet / project
     dossier — blueprint grid, corner-bracket cards, mono index labels,
     a sticky spec card, and a connected process schematic. Built for
     MSN Softtech's existing navy + mint + amber identity, but with a
     completely new structure, typography system and interactions.
============================================================ --}}

@section('content')

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">

<style>
  .svc-page{
    --ink:#071a2b;
    --ink-2:#0d2946;
    --ink-3:#123457;
    --paper:#FCFDFF;
    --card:#ffffff;
    --mint:#2be7a6;
    --amber:#f2a93b;
    --slate:#16202c;
    --muted:#5c6b7a;
    --line:rgba(255,255,255,.14);
    --line-soft:rgba(7,26,43,.1);
    --shadow:0 24px 60px -30px rgba(7,26,43,.35);
    font-family:'Inter',sans-serif;
    color:var(--slate);
    background:var(--paper);
    overflow-x:clip;
  }
  .svc-page *{box-sizing:border-box;}
  .svc-page h1,.svc-page h2,.svc-page h3{
    font-family:'Space Grotesk',sans-serif;
    letter-spacing:-0.01em;
    margin:0;
  }
  .svc-page .mono{
    font-family:'JetBrains Mono',monospace;
  }
  .svc-container{
    max-width:1180px;
    margin:0 auto;
    padding:0 24px;
  }
  .svc-page a{text-decoration:none;color:inherit;}
  .svc-page ul{margin:0;padding:0;list-style:none;}
  .svc-page img{max-width:100%;display:block;}

  /* ---------- reveal-on-scroll ---------- */
  .svc-reveal{opacity:0;transform:translateY(18px);transition:opacity .7s ease,transform .7s ease;}
  .svc-reveal.is-in{opacity:1;transform:none;}
  @media (prefers-reduced-motion:reduce){
    .svc-reveal{opacity:1;transform:none;transition:none;}
  }

  /* ================= HERO ================= */
  .svc-hero{
    position:relative;
    background:radial-gradient(1100px 480px at 85% -10%, rgba(43,231,166,.14), transparent 60%),
               linear-gradient(160deg,var(--ink),#04101d 70%);
    padding:64px 0 48px;
    color:#fff;
    overflow:hidden;
  }
  .svc-hero__grid{
    position:absolute;inset:0;
    background-image:
      linear-gradient(rgba(255,255,255,.05) 1px, transparent 1px),
      linear-gradient(90deg, rgba(255,255,255,.05) 1px, transparent 1px);
    background-size:44px 44px;
    -webkit-mask-image:linear-gradient(180deg, rgba(0,0,0,.9), transparent 85%);
            mask-image:linear-gradient(180deg, rgba(0,0,0,.9), transparent 85%);
    pointer-events:none;
  }
  .svc-breadcrumb{
    position:relative;
    display:flex;gap:8px;align-items:center;
    font-size:12.5px;color:rgba(255,255,255,.55);
    margin-bottom:28px;
  }
  .svc-breadcrumb a{color:rgba(255,255,255,.8);}
  .svc-breadcrumb a:hover{color:var(--mint);}
  .svc-hero__row{
    position:relative;
    display:grid;
    grid-template-columns:1.55fr 1fr;
    gap:48px;
    align-items:start;
  }
  .svc-eyebrow{
    display:inline-flex;align-items:center;gap:10px;
    font-size:12px;letter-spacing:.16em;text-transform:uppercase;
    color:var(--mint);
    padding-bottom:16px;
  }
  .svc-eyebrow::before{
    content:'';width:22px;height:1px;background:var(--mint);display:inline-block;
  }
  .svc-hero h1{
    font-size:clamp(2.1rem,4.4vw,3.35rem);
    line-height:1.06;
    font-weight:700;
    color:#fff;
    max-width:16ch;
  }
  .svc-hero__desc{
    margin-top:20px;
    font-size:17px;
    line-height:1.7;
    color:rgba(255,255,255,.68);
    max-width:52ch;
  }
  .svc-hero__ctas{
    display:flex;flex-wrap:wrap;gap:14px;
    margin-top:32px;
  }
  .btn-amber{
    background:var(--amber);
    color:#1a1204;
    border:none;
    font-family:'Space Grotesk',sans-serif;
    font-weight:600;
    font-size:14.5px;
    padding:14px 26px;
    border-radius:8px;
    cursor:pointer;
    transition:transform .2s ease, box-shadow .2s ease;
    box-shadow:0 12px 24px -10px rgba(242,169,59,.55);
  }
  .btn-amber:hover{transform:translateY(-2px);box-shadow:0 16px 30px -10px rgba(242,169,59,.7);}
  .btn-ghost{
    display:inline-flex;align-items:center;gap:8px;
    border:1px solid var(--line);
    color:#fff;
    font-family:'Space Grotesk',sans-serif;
    font-weight:600;
    font-size:14.5px;
    padding:13px 22px;
    border-radius:8px;
    transition:border-color .2s ease, background .2s ease;
  }
  .btn-ghost:hover{border-color:var(--mint);background:rgba(43,231,166,.08);color:#fff;}

  .svc-stat-row{
    display:flex;gap:34px;margin-top:44px;flex-wrap:wrap;
    border-top:1px solid var(--line);
    padding-top:24px;
  }
  .svc-stat b{
    display:block;font-family:'Space Grotesk',sans-serif;font-size:26px;color:#fff;
  }
  .svc-stat span{
    font-size:12px;letter-spacing:.06em;text-transform:uppercase;color:rgba(255,255,255,.5);
  }

  /* ---- spec card (signature element) ---- */
  .svc-spec{
    position:relative;
    background:linear-gradient(180deg,var(--ink-3),var(--ink-2));
    border:1px solid var(--line);
    border-radius:4px;
    padding:26px 24px;
  }
  .svc-spec::before,.svc-spec::after,
  .svc-spec .bl,.svc-spec .br{
    content:'';position:absolute;width:16px;height:16px;
    border-color:var(--mint);border-style:solid;border-width:0;
  }
  .svc-spec::before{top:-1px;left:-1px;border-top-width:2px;border-left-width:2px;}
  .svc-spec::after{top:-1px;right:-1px;border-top-width:2px;border-right-width:2px;}
  .svc-spec .bl{bottom:-1px;left:-1px;border-bottom-width:2px;border-left-width:2px;}
  .svc-spec .br{bottom:-1px;right:-1px;border-bottom-width:2px;border-right-width:2px;}
  .svc-spec__thumb{
    width:100%;aspect-ratio:16/11;object-fit:cover;border-radius:2px;margin-bottom:20px;
    border:1px solid var(--line);
  }
  .svc-spec__label{
    font-size:11px;color:var(--mint);letter-spacing:.14em;text-transform:uppercase;margin-bottom:10px;
  }
  .svc-spec__rows{border-top:1px solid var(--line);}
  .svc-spec__row{
    display:flex;justify-content:space-between;gap:10px;
    padding:12px 0;border-bottom:1px solid var(--line);
    font-size:13.5px;
  }
  .svc-spec__row dt{color:rgba(255,255,255,.5);}
  .svc-spec__row dd{margin:0;color:#fff;font-weight:500;text-align:right;}
  .svc-spec__cta{
    display:block;text-align:center;margin-top:20px;
    background:var(--mint);color:#04241a;font-weight:700;
    font-family:'Space Grotesk',sans-serif;font-size:14px;
    padding:13px;border-radius:6px;border:none;width:100%;cursor:pointer;
    transition:filter .2s ease;
  }
  .svc-spec__cta:hover{filter:brightness(1.08);}

  @media (max-width:960px){
    .svc-hero__row{grid-template-columns:1fr;}
  }

  /* ================= SUBNAV ================= */
  .svc-subnav-wrap{
    position:sticky;top:0;z-index:30;
    background:rgba(246,244,238,.9);
    backdrop-filter:blur(10px);
    border-bottom:1px solid var(--line-soft);
  }
  .svc-subnav{
    display:flex;gap:4px;overflow-x:auto;
    padding:12px 24px;
    scrollbar-width:none;
  }
  .svc-subnav::-webkit-scrollbar{display:none;}
  .svc-subnav a{
    white-space:nowrap;
    font-size:13.5px;font-weight:500;color:var(--muted);
    padding:8px 14px;border-radius:20px;
    transition:background .2s ease,color .2s ease;
  }
  .svc-subnav a.is-active,.svc-subnav a:hover{
    background:var(--ink);color:#fff;
  }

  /* ================= LAYOUT ================= */
  .svc-layout{
    display:grid;
    grid-template-columns:1.6fr 1fr;
    gap:56px;
    padding:56px 24px 20px;
    align-items:start;
  }
  .svc-layout__aside{
    position:sticky;top:74px;
    display:flex;flex-direction:column;gap:20px;
  }
  @media (max-width:960px){
    .svc-layout{grid-template-columns:1fr;padding:40px 20px 0;}
    .svc-layout__aside{position:static;order:-1;}
  }

  .svc-block{margin-bottom:64px;scroll-margin-top:96px;}
  .svc-block__head{margin-bottom:24px;}
  .svc-block__index{
    font-size:12px;color:var(--muted);letter-spacing:.14em;
    display:block;margin-bottom:8px;
  }
  .svc-block h2{font-size:clamp(1.5rem,2.6vw,2rem);color:var(--slate);}

  .svc-prose{font-size:16px;line-height:1.85;color:#2c3744;}
  .svc-prose :where(h2,h3,h4){font-family:'Space Grotesk',sans-serif;color:var(--slate);margin:28px 0 12px;}
  .svc-prose p{margin:0 0 16px;}
  .svc-prose ul{list-style:disc;padding-left:22px;margin-bottom:16px;}
  .svc-prose img{border-radius:8px;margin:20px 0;}
  .svc-prose a{color:var(--ink-3);text-decoration:underline;text-underline-offset:3px;}

  /* checklist */
  .svc-checklist{display:grid;gap:12px;}
  .svc-checklist li{
    display:flex;gap:14px;align-items:flex-start;
    background:var(--card);
    border:1px solid var(--line-soft);
    border-radius:10px;
    padding:16px 18px;
    font-size:15px;
  }
  .svc-check-ic{
    flex:none;width:22px;height:22px;border-radius:50%;
    background:rgba(43,231,166,.15);
    display:flex;align-items:center;justify-content:center;
    margin-top:1px;
  }
  .svc-check-ic svg{width:12px;height:12px;}

  /* tag cloud */
  .svc-tags{display:flex;flex-wrap:wrap;gap:10px;}
  .svc-tags a,.svc-tags span{
    font-size:13.5px;font-weight:500;
    padding:9px 16px;border-radius:20px;
    border:1px solid var(--line-soft);
    background:var(--card);
    color:var(--slate);
    transition:border-color .2s ease,color .2s ease;
  }
  .svc-tags a:hover{border-color:var(--ink-3);color:var(--ink-3);}

  /* contact rail card */
  .svc-contact-card{
    background:var(--card);
    border:1px solid var(--line-soft);
    border-radius:10px;
    padding:20px;
  }
  .svc-contact-card h3{font-size:14px;margin-bottom:14px;}
  .svc-contact-row{display:flex;flex-direction:column;gap:8px;}
  .svc-contact-row a{
    display:flex;align-items:center;gap:10px;
    font-size:13.5px;font-weight:500;
    padding:10px 12px;border-radius:8px;
    background:var(--paper);
    transition:background .2s ease;
  }
  .svc-contact-row a:hover{background:#eee9dd;}
  .svc-contact-row img{width:18px;height:18px;}

  /* ================= PROCESS ================= */
  .svc-process{
    background:var(--ink);
    color:#fff;
    padding:80px 0;
    position:relative;
  }
  .svc-process .svc-block__index{color:rgba(255,255,255,.45);}
  .svc-process h2{color:#fff;}
  .svc-process__lead{color:rgba(255,255,255,.6);max-width:56ch;margin-top:12px;font-size:15.5px;line-height:1.7;}
  .svc-flow{
    margin-top:48px;
    display:grid;
    grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
    gap:0;
  }
  .svc-flow__step{
    position:relative;
    padding:0 22px 0 0;
  }
  .svc-flow__num{
    font-family:'JetBrains Mono',monospace;
    font-size:12px;color:var(--mint);
    display:flex;align-items:center;gap:10px;
    margin-bottom:14px;
  }
  .svc-flow__num::after{
    content:'';flex:1;height:1px;background:var(--line);
  }
  .svc-flow__step h4{font-family:'Space Grotesk',sans-serif;font-size:16.5px;margin-bottom:8px;color:#fff;}
  .svc-flow__step p{font-size:13.5px;line-height:1.65;color:rgba(255,255,255,.55);}
  @media (min-width:769px){
    .svc-flow__step:not(:last-child)::before{
      content:'';position:absolute;top:5px;right:0;width:22px;height:1px;
      background:repeating-linear-gradient(to right,var(--mint) 0 4px,transparent 4px 8px);
    }
  }
  .svc-process__cta{margin-top:52px;text-align:center;}

  /* ================= FAQ ================= */
  .svc-faq{padding:80px 0;}
  .svc-faq__list{max-width:820px;margin:0 auto;}
  .svc-faq__item{
    border-bottom:1px solid var(--line-soft);
    padding:22px 0;
  }
  .svc-faq__q{
    display:flex;justify-content:space-between;align-items:center;gap:20px;
    cursor:pointer;
  }
  .svc-faq__q .n{
    font-family:'JetBrains Mono',monospace;color:var(--muted);font-size:13px;margin-right:14px;
  }
  .svc-faq__q h4{font-family:'Space Grotesk',sans-serif;font-weight:600;font-size:16px;color:var(--slate);flex:1;}
  .svc-faq__plus{
    flex:none;width:22px;height:22px;position:relative;
  }
  .svc-faq__plus::before,.svc-faq__plus::after{
    content:'';position:absolute;background:var(--ink-3);
    top:50%;left:50%;transform:translate(-50%,-50%);
  }
  .svc-faq__plus::before{width:12px;height:2px;}
  .svc-faq__plus::after{width:2px;height:12px;transition:transform .25s ease;}
  .svc-faq__item.is-open .svc-faq__plus::after{transform:translate(-50%,-50%) rotate(90deg) scaleY(0);}
  .svc-faq__a{
    max-height:0;overflow:hidden;
    transition:max-height .3s ease;
    padding-left:37px;
  }
  .svc-faq__a p{font-size:14.5px;line-height:1.75;color:var(--muted);margin:14px 0 0;}
  .svc-faq__item.is-open .svc-faq__a{max-height:400px;}

  /* ================= FINAL CTA ================= */
  .svc-final{
    position:relative;
    background:linear-gradient(160deg,var(--ink),#04101d 70%);
    color:#fff;padding:80px 0;overflow:hidden;
  }
  .svc-final__inner{
    position:relative;
    text-align:center;max-width:620px;margin:0 auto;
  }
  .svc-final h2{color:#fff;font-size:clamp(1.6rem,3vw,2.3rem);}
  .svc-final p{color:rgba(255,255,255,.6);margin-top:14px;font-size:15.5px;}
  .svc-final .btn-amber{margin-top:28px;}
  .svc-final__contact{
    display:none;
    gap:12px;justify-content:center;margin-top:28px;flex-wrap:wrap;
  }
  .svc-final__contact a{
    display:flex;align-items:center;gap:8px;
    border:1px solid var(--line);
    padding:10px 16px;border-radius:8px;font-size:13.5px;
  }
  .svc-final__contact img{width:16px;height:16px;}
  @media (max-width:960px){
    .svc-final__contact{display:flex;}
  }
</style>

<div class="svc-page">

  {{-- ===== HERO ===== --}}
  <section class="svc-hero">
    <div class="svc-hero__grid" aria-hidden="true"></div>
    <div class="svc-container">
      <div class="svc-breadcrumb">
        <a href="{{ route('home') }}">{{ __('navbar.home') }}</a>
        <span>/</span>
        <span style="color:#fff">{{ $service->title }}</span>
      </div>

      <div class="svc-hero__row">
        <div>
          <span class="svc-eyebrow mono">Service Dossier</span>
          <h1>{{ $service->title }}</h1>
          @if(isset($service->short_desc))
            <p class="svc-hero__desc">{!! strip_tags($service->short_desc) !!}</p>
          @endif

          <div class="svc-hero__ctas">
            <button type="button" id="open-modal" class="btn-amber">Discuss Your Requirements →</button>
            <a href="#overview" class="btn-ghost">Read the Full Scope</a>
          </div>

          <div class="svc-stat-row">
            @if(isset($service->average_rating))
              <div class="svc-stat">
                <b class="svc-counter" data-target="{{ $service->average_rating }}" data-decimals="1">0</b>
                <span>Avg. Rating</span>
              </div>
            @endif
            @if(isset($service->review_count))
              <div class="svc-stat">
                <b class="svc-counter" data-target="{{ $service->review_count }}">0</b>
                <span>Client Reviews</span>
              </div>
            @endif
            <div class="svc-stat">
              <b class="svc-counter" data-target="10">0</b>
              <span>Years Delivering</span>
            </div>
            <div class="svc-stat">
              <b class="svc-counter" data-target="3700">0</b>
              <span>Projects Shipped</span>
            </div>
          </div>
        </div>

        <aside class="svc-spec">
          <span class="bl" aria-hidden="true"></span><span class="br" aria-hidden="true"></span>
          <img class="svc-spec__thumb" src="{{ asset('uploads/service/' . $service->image_path) }}" alt="{{ $service->title }}">
          <div class="svc-spec__label mono">Quick Facts</div>
          <dl class="svc-spec__rows">
            <div class="svc-spec__row"><dt>Category</dt><dd>{{ $service->short_title ?? $service->title }}</dd></div>
            <div class="svc-spec__row"><dt>Engagement</dt><dd>Fixed / Milestone / Monthly</dd></div>
            <div class="svc-spec__row"><dt>Kickoff Reply</dt><dd>Within 24 hours</dd></div>
            @if(isset($service->average_rating))
              <div class="svc-spec__row"><dt>Client Rating</dt><dd>{{ $service->average_rating }} / 5</dd></div>
            @endif
          </dl>
          <button type="button" class="svc-spec__cta" onclick="document.getElementById('open-modal')?.click()">Get a Tailored Quote</button>
        </aside>
      </div>
    </div>
  </section>

  {{-- ===== SUBNAV ===== --}}
  <div class="svc-subnav-wrap">
    <nav class="svc-subnav mono" id="svc-subnav">
      <a href="#overview">Overview</a>
      @if ($service->whywes->count() > 0)<a href="#why-us">Why Us</a>@endif
      @if ($service->industries->count() > 0)<a href="#industries">Industries</a>@endif
      @if ($service->processworks->count() > 0)<a href="#svc-process">Process</a>@endif
      @if ($service->faqs->count() > 0)<a href="#svc-faq">FAQ</a>@endif
    </nav>
  </div>

  @if(isset($service))
    <div class="svc-container">
      <div class="svc-layout">

        {{-- ===== MAIN COLUMN ===== --}}
        <div class="svc-layout__main">

          <section id="overview" class="svc-block svc-reveal">
            <div class="svc-block__head">
              <span class="svc-block__index mono">§ 01 — Overview</span>
              <h2>{{ $service->short_title }}</h2>
            </div>
            <div id="processedContent" class="svc-prose">
              {!! $service->description !!}
            </div>
          </section>

          @if ($service->whywes->count() > 0)
            <section id="why-us" class="svc-block svc-reveal">
              <div class="svc-block__head">
                <span class="svc-block__index mono">§ 02 — Why Us</span>
                <h2>Why Choose MSN Softtech</h2>
              </div>
              <ul class="svc-checklist">
                @foreach($service->whywes as $we)
                  <li>
                    <span class="svc-check-ic">
                      <svg viewBox="0 0 16 16" fill="none"><path d="M2 8.5L6 12L14 4" stroke="#0e8f5c" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                    </span>
                    @if($we->link)
                      <a target="_blank" href="{{ $we->link }}" style="text-decoration:underline;">{{ $we->title }}</a>
                    @else
                      <span>{{ $we->title }}</span>
                    @endif
                  </li>
                @endforeach
              </ul>
            </section>
          @endif

          @if ($service->industries->count() > 0)
            <section id="industries" class="svc-block svc-reveal">
              <div class="svc-block__head">
                <span class="svc-block__index mono">§ 03 — Industries</span>
                <h2>Industries We Serve</h2>
              </div>
              <div class="svc-tags">
                @foreach($service->industries as $industry)
                  @if($industry->link)
                    <a target="_blank" href="{{ $industry->link }}">{{ $industry->title }}</a>
                  @else
                    <span>{{ $industry->title }}</span>
                  @endif
                @endforeach
              </div>
            </section>
          @endif

        </div>

        {{-- ===== ASIDE ===== --}}
        <div class="svc-layout__aside">
          @php
            $page_quote = \App\Models\PageSetup::page('get-quote');
            $page_contact = \App\Models\PageSetup::page('contact-us');
          @endphp
          <div class="svc-contact-card svc-reveal">
            <h3 class="mono">Talk To Us Directly</h3>
            <div class="svc-contact-row">
              @if(isset($page_quote))
                <a href="{{ route('get-quote') }}" target="_blank">
                  <img src="https://cdn-icons-png.flaticon.com/128/18572/18572275.png" alt="Get A Quote">
                  Get a Free Quote
                </a>
              @elseif(isset($page_contact))
                <a href="{{ route('contact') }}">{{ __('common.get_start') }}</a>
              @endif
              <a rel="noopener noreferrer" href="https://wa.link/vkb4au" target="_blank">
                <img src="https://cdn-icons-png.flaticon.com/128/733/733585.png" alt="WhatsApp">
                Chat on WhatsApp
              </a>
              <a href="mailto:{{ $setting->email_one }}?subject=Inquiry&body=Hello, I need your services.">
                <img src="https://cdn-icons-png.flaticon.com/128/732/732200.png" alt="Email">
                Email Our Team
              </a>
            </div>
          </div>
          <div class="svc-reveal">
            @include('web.layouts.googlemeet')
          </div>
        </div>

      </div>
    </div>
  @endif

  {{-- ===== PROCESS ===== --}}
  @if ($service->processworks->count() > 0)
    <section id="svc-process" class="svc-process">
      <div class="svc-container">
        <div class="svc-block__head svc-reveal">
          <span class="svc-block__index mono">§ 04 — Process</span>
          <h2>How We Deliver {{ $service->short_title }}</h2>
          <p class="svc-process__lead">A transparent, staged workflow — every step is tracked, reviewed and signed off before the next one begins.</p>
        </div>

        <div class="svc-flow">
          @foreach ($service->processworks as $key => $process)
            <div class="svc-flow__step svc-reveal">
              <div class="svc-flow__num">{{ sprintf('%02d', $key + 1) }}</div>
              <h4>{{ $process->title }}</h4>
              <p>{{ $process->description }}</p>
            </div>
          @endforeach
        </div>

        <div class="svc-process__cta svc-reveal">
          <a href="https://msnsofttech.com/get-quote" class="btn-amber">Get in Touch With Us →</a>
        </div>
      </div>
    </section>
  @endif

  {{-- ===== FAQ ===== --}}
  @if ($service->faqs->count() > 0)
    <section id="svc-faq" class="svc-faq">
      <div class="svc-container">
        <div class="svc-block__head svc-reveal">
          <span class="svc-block__index mono">§ 05 — Clarifications</span>
          <h2>Frequently Asked Questions</h2>
        </div>
        <div class="svc-faq__list">
          @foreach ($service->faqs as $key => $item)
            <div class="svc-faq__item svc-reveal">
              <div class="svc-faq__q">
                <span class="n mono">{{ sprintf('%02d', $key + 1) }}</span>
                <h4>{{ $item->title }}</h4>
                <span class="svc-faq__plus" aria-hidden="true"></span>
              </div>
              <div class="svc-faq__a">
                <p>{{ $item->description }}</p>
              </div>
            </div>
          @endforeach
        </div>
      </div>
    </section>
  @endif



</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {

    // ---- "hidden" content split (kept from original CMS behaviour) ----
    var descBox = document.getElementById("processedContent");
    if (descBox) {
      var descriptionContent = descBox.innerHTML;
      var idx = descriptionContent.toLowerCase().indexOf("hidden");
      if (idx !== -1) {
        var visible = descriptionContent.substring(0, idx);
        var hidden = descriptionContent.substring(idx);
        descBox.innerHTML = visible + "<span class='hidden'>" + hidden + "</span>";
      }
    }

    // ---- FAQ accordion ----
    document.querySelectorAll('.svc-faq__item').forEach(function (item) {
      var q = item.querySelector('.svc-faq__q');
      q.addEventListener('click', function () {
        var wasOpen = item.classList.contains('is-open');
        document.querySelectorAll('.svc-faq__item').forEach(function (i) { i.classList.remove('is-open'); });
        if (!wasOpen) item.classList.add('is-open');
      });
    });

    // ---- scroll reveal ----
    var revealEls = document.querySelectorAll('.svc-reveal');
    if ('IntersectionObserver' in window) {
      var io = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (e.isIntersecting) { e.target.classList.add('is-in'); io.unobserve(e.target); }
        });
      }, { threshold: 0.12 });
      revealEls.forEach(function (el) { io.observe(el); });
    } else {
      revealEls.forEach(function (el) { el.classList.add('is-in'); });
    }

    // ---- animated counters ----
    var counters = document.querySelectorAll('.svc-counter');
    var counted = false;
    function runCounters() {
      if (counted) return;
      counted = true;
      counters.forEach(function (el) {
        var target = parseFloat(el.getAttribute('data-target')) || 0;
        var decimals = parseInt(el.getAttribute('data-decimals') || '0', 10);
        var start = 0;
        var duration = 1100;
        var startTime = null;
        function step(ts) {
          if (!startTime) startTime = ts;
          var progress = Math.min((ts - startTime) / duration, 1);
          var value = start + (target - start) * progress;
          el.textContent = decimals ? value.toFixed(decimals) : Math.floor(value);
          if (progress < 1) requestAnimationFrame(step);
          else el.textContent = decimals ? target.toFixed(decimals) : target;
        }
        requestAnimationFrame(step);
      });
    }
    var statRow = document.querySelector('.svc-stat-row');
    if (statRow && 'IntersectionObserver' in window) {
      new IntersectionObserver(function (entries, obs) {
        entries.forEach(function (e) { if (e.isIntersecting) { runCounters(); obs.disconnect(); } });
      }, { threshold: 0.4 }).observe(statRow);
    } else {
      runCounters();
    }

    // ---- subnav scrollspy ----
    var subnavLinks = document.querySelectorAll('#svc-subnav a');
    var sections = Array.prototype.map.call(subnavLinks, function (a) {
      return document.querySelector(a.getAttribute('href'));
    }).filter(Boolean);

    function onScroll() {
      var pos = window.scrollY + 120;
      var current = sections[0];
      sections.forEach(function (sec) { if (sec.offsetTop <= pos) current = sec; });
      subnavLinks.forEach(function (a) {
        a.classList.toggle('is-active', a.getAttribute('href') === '#' + current.id);
      });
    }
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();
  });
</script>

@endsection
